# Doména projektu — odkaz na domains/<MHN>/<typ>.conf.
domain=MHN9/online
repository_teams=test-gov-admins|admin
repository_creators=test-gov-outsiders
repository_archivers=test-gov-outsiders
rulesets=default
