# Doména projektu — odkaz na domains/<MHN>/<typ>.conf.
domain=MHN8/batch
repository_teams=test-gov-admins|admin
repository_creators=test-gov-admins
repository_archivers=test-gov-admins
rulesets=default
