# Doména projektu — odkaz na domains/<MHN>/<typ>.conf.
domain=MHN9/online
repository_teams=test-gov-admins|admin,test-gov-outsiders|push
repository_creators=test-gov-admins
repository_archivers=test-gov-admins
rulesets=default,release
